settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: go-webhook
  path: .
  env:
    CURLHOOK_REDIS_CLUSTER: true
    CURLHOOK_REDIS_HOST: "localhost"
    CURLHOOK_REDIS_PORT: "6379"
    CURLHOOK_REDIS_PASSWORD: ""
  commands:
    install:
      status: true
      method: go install
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
