settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: go-webhook
  path: ./app
  env:
    WEBHOOK_MESSAGE_QUEUE_REDIS_CLUSTER: true
    WEBHOOK_MESSAGE_QUEUE_REDIS_HOST: "localhost"
    WEBHOOK_MESSAGE_QUEUE_REDIS_PORT: "6379"
    WEBHOOK_MESSAGE_QUEUE_REDIS_PASSWORD: ""
  commands:
    install:
      status: true
      method: go install
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
