enabled: true
port: 3000
retry: 10
retry_mechanism: "backoff"
no_of_worker: 2
max_pending_webhook: 10000

grpc:
  enabled: true # enable gRPC server
  api_key: "abcd"
  port: 9000

message_queue:
  engine: "redis"
  topic: "webhook"
  queue_group: "webhook"
  redis:
    cluster: false
    addr: "127.0.0.1:6379"
    password: ""
    db: 1
  nats:
    js: true
    stream: "webhook"
    queue: "webhook"