# HTTP server
enabled: true
port: 3000
no_of_worker: 2
max_pending_webhook: 10000

monitor:
  enabled: true

# gRPC server
grpc:
  enabled: true # enable gRPC server
  api_key: "abcd"
  port: 9000

# Database - Elasticsearch
elasticsearch:
  host: "http://localhost:9200"
  index_name: ""
  username: ""
  password: ""

db:
  engine: "elasticsearch"

message_queue:
  engine: "redis" # possible value is redis, nats, nsq
  topic: "webhook"
  queue_group: "webhook"
  redis:
    cluster: false
    addr: "127.0.0.1:6379"
    password: ""
    db: 1
  nats:
    js: true # indicate whether use jetstream or not
    stream: "webhook"
    queue: "webhook"