enabled: false
port: 3000
retry: 10
retry_mechanism: "backoff"
no_of_worker: 1
max_pending_webhook: 10000

grpc:
  enabled: false # enable gRPC server
  port: 9000

message_queue:
  nats:
    js: true
    stream: "webhook"
    queue: "webhook"