apiVersion: v1
kind: Service
metadata:
  name: webhook
  labels:
    app: webhook
spec:
  ports:
    # HTTP/RESTful server
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    # gRPC server
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: grpc
    # webhook UI
  type: NodePort
  selector:
    app: webhook

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  labels:
    app: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      imagePullSecrets:
        - name: regsecret
      terminationGracePeriodSeconds: 60
      containers:
        - name: webhook
          image: 
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
            - containerPort: 9000
          # envFrom:
          #   - configMapRef:
          #       name: 
          # env:
          #   - name: PORT
          #     value: "5001"

