apiVersion: v1
kind: Service
metadata:
  name: webhook
  labels:
    app: webhook
spec:
  ports:
    # HTTP/rest server
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    # Monitor APIs
    - port: 3222
      targetPort: 3222
      protocol: TCP
      name: monitor
    # gRPC server
    - port: 5222
      targetPort: 5222
      protocol: TCP
      name: grpc
  type: ClusterIP
  selector:
    app: webhook

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  labels:
    app: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: webhook
          image: webhook
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 3222
              name: monitor
            - containerPort: 5222
              name: grpc
          # envFrom:
          #   - configMapRef:
          #       name: 
          env:
            - name: PORT
              value: "5001"

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5


