name: Testing
on:
  push:
    branches:
      - main

jobs:
  build-go:
    name: Build Go
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
          fi

      - name: Test Data Race
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Codecov
        uses: codecov/codecov-action@v2.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  # codecov:
  #   needs: [ checkout ]
  #   name: Codecov
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Codecov
  #       uses: codecov/codecov-action@v2.0.3
  #       with:
  #         token: ${{secrets.CODECOV_TOKEN}}

